package com.gigavoid.supermod.worldgen;

import java.util.ArrayList;
import java.util.List;

import com.gigavoid.supermod.SuperMod;
import com.gigavoid.supermod.biome.SuperBiomes;
import net.minecraft.util.WeightedRandom;
import net.minecraft.world.WorldType;
import net.minecraft.world.biome.BiomeGenBase;
import net.minecraft.world.gen.layer.*;
import net.minecraftforge.common.BiomeManager;
import net.minecraftforge.common.BiomeManager.BiomeEntry;

public class NorthrendGenLayerBiome extends GenLayer
{
    private List<BiomeEntry>[] biomes = new ArrayList[BiomeManager.BiomeType.values().length];

    private static final String __OBFID = "CL_00000555";

    public NorthrendGenLayerBiome(long p_i2122_1_, GenLayer p_i2122_3_, WorldType p_i2122_4_)
    {
        super(p_i2122_1_);
    }

    /**
     * Returns a list of integer values generated by this layer. These may be interpreted as temperatures, rainfall
     * amounts, or biomeList[] indices based on the particular GenLayer subclass.
     */
    public int[] getInts(int p_75904_1_, int p_75904_2_, int p_75904_3_, int p_75904_4_)
    {
        int[] aint1 = IntCache.getIntCache(p_75904_3_ * p_75904_4_);

        for (int i1 = 0; i1 < p_75904_4_; ++i1)
        {
            for (int j1 = 0; j1 < p_75904_3_; ++j1)
            {
                this.initChunkSeed((long)(j1 + p_75904_1_), (long)(i1 + p_75904_2_));
                aint1[j1 + i1 * p_75904_3_] = 41 + this.nextInt(3);
            }
        }

        return aint1;
    }

    public static GenLayer[] initializeAllBiomeGenerators(long p_75901_0_, WorldType p_75901_2_)  {
        NorthrendGenLayerBiome goodLayer = new NorthrendGenLayerBiome(1000, null, null);
        GenLayer zoom = GenLayerZoom.magnify(1000L, goodLayer, 4);

        return new GenLayer[] {zoom, zoom, zoom};
    }

}